steps:
- script: |
    sudo cp .azure-pipelines/linux/xvfb.init /etc/init.d/xvfb
    sudo chmod +x /etc/init.d/xvfb
    sudo update-rc.d xvfb defaults
    sudo service xvfb start
  displayName: 'Start X Virtual Frame Buffer'
  condition: eq(variables['Agent.OS'], 'Linux')

- task: Npm@1
  displayName: 'Test'
  inputs:
    command: custom
    customCommand: run test
  env:
    DISPLAY: :10 # Only necessary for linux tests
    VSCODE_DAPR_IGNORE_BUNDLE: true
