jobs:
- job: Windows
  pool:
    vmImage: windows-latest
  steps:
  - template: common/setup.yml
  - template: common/governance.yml   # Force governance before test to avoid false-positives.
  - template: common/build.yml

- job: Linux
  pool:
    vmImage: ubuntu-latest
  steps:
  - template: common/setup.yml
  - template: common/governance.yml   # Force governance before test to avoid false-positives.
  - template: common/publish-vsix.yml # Only publish vsix from linux build since we use this to release and want to stay consistent

- job: macOS
  pool:
    vmImage: macOS-latest
  steps:
  - template: common/setup.yml
  - template: common/governance.yml   # Force governance before test to avoid false-positives.
  - template: common/build.yml
